---
coverage:
  status:
    project: false
    patch: false

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: api
      name: API
      paths:
        - src/pytermite/
        - '!src/pytermite/pytermite.py'
      statuses:
        - type: project
          target: 100%
          threshold: 1%
    - component_id: cli
      name: CLI
      paths:
        - src/pytermite/pytermite.py
      statuses:
        - type: project
          target: auto
          threshold: 1%
