[tox]
requires = tox>=4.0
env_list =
    pre-commit
    clean
    py3.1{2,3}
    report
    build
    sphinx
skip_missing_interpreters = true
set_env =
    TEMP = {env_tmp_dir}

[testenv]
description = run the test suite
deps =
    pytest
    pytest-asyncio
    pytest-mock
    pytest-cov
    pytest-random-order
    pytest-sugar
package = editable
wheel_build_env = .pkg
depends =
    py3.1{2,3}: clean
    report: py3.1{2,3}
commands =
    pytest {posargs:tests}

[testenv:pre-commit]
description = run pre-commit hooks
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files {posargs}

[testenv:clean]
description = clean up temporary files
base_python = py3.12
skip_install = true
deps =
    coverage
commands = coverage erase

[testenv:report]
description = generate test coverage report
deps = coverage
base_python = py3.12
skip_install = true
commands =
    coverage report
    coverage xml

[testenv:build]
description = build source and wheel packages
skip_install = true
base_python = py3.12
deps =
    build
    setuptools
commands =
    python -m build --outdir dist

[testenv:sphinx]
description = build the Sphinx documentation
skip_install = true
base_python = py3.12
depends =
    pre-commit
deps =
    sphinx
    pydata-sphinx-theme
    sphinxcontrib-email
    sphinx_copybutton
    numpydoc
commands =
    sphinx-build -b html docs/source docs/build/html
