---
defaults:
  run:
    shell: bash

name: CI
run-name: Run CI for ${{ github.ref_name }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: false
        type: string
  workflow_dispatch:

jobs:
  run-lints:
    name: Lint Code
    uses: ./.github/workflows/lint.yml

  run-tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs: [run-lints, run-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Generate a full changelog
        uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff
        id: git-cliff-full
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Setup Python 3.12
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: 3.12

      - name: Format with mdformat
        run: |
          pip install mdformat mdformat-gfm
          mdformat CHANGELOG.md

      - name: Set target branch for changelog commit
        id: set-branch
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "${{ inputs.version }}" != "" ]]; then
            echo "branch=main" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Commit full changelog
        id: commit-changelog
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: planetscale/ghcommit-action@a6b150b81dca5dd027baa898604418eec9e11465
        with:
          commit_message: "chore: update changelog"
          repo: ${{ github.repository }}
          branch: ${{ steps.set-branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Generate a release changelog
        uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff
        if: ${{ inputs.version }}
        id: git-cliff-release
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Upload changelog
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ inputs.version }}
        id: upload-changelog
        with:
          name: Changes
          path: CHANGES.md
          if-no-files-found: error

  dist:
    name: Build distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    needs: generate-changelog
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Build and inspect the Python package
        uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5

  install:
    name: Check version
    runs-on: ubuntu-latest
    needs: dist
    steps:
      - name: Get artifacts from dist job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: Packages
          path: ./dist

      - name: Set up Python 3.12
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: 3.12

      - name: Install the built package
        id: install-package
        run: |
          pip install dist/pytermite-*.whl
          version=$(python -c "import pytermite; print(pytermite.get_version())")
          echo "Installed pyTermite version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if the installed package version matches the workflow input
        if: ${{ inputs.version && inputs.version != '' }}
        id: check-version
        run: |
          if [[ "$version" != "${{ inputs.version }}" ]]; then
            echo "Version mismatch: Installed pyTermite has version $version
            but workflow input is ${{ inputs.version }}"
            exit 1
          fi
        env:
          version: ${{ steps.install-package.outputs.version }}
